name: CI
permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: build (${{ matrix.name }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # ---------- Linux ----------
          - name: linux-x86_64
            os: ubuntu-latest
            arch: x86_64

          # ---------- Windows ----------
          - name: windows-x86_64
            os: windows-latest
            arch: x86_64

          # ---------- macOS Intel ----------
          - name: macos-x86_64
            os: macos-15-intel
            arch: x86_64

          # ---------- macOS Apple Silicon ----------
          - name: macos-aarch64
            os: macos-latest
            arch: aarch64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1

      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Install cranelift codegen
        run: rustup component add rustc-codegen-cranelift-preview --toolchain nightly

      - name: Cache build dir
        uses: actions/cache@v5
        with:
          path: target
          key: cargo-${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ matrix.arch }}-

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y mold libasound2-dev libglib2.0-dev pkg-config

      - name: Install system dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update

      - name: Build debug
        run: cargo build --verbose

      - name: Build release
        run: cargo build --release --verbose

      - name: Build small release
        run: cargo build --profile=release-small --verbose

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v6
        with:
          name: debug-${{ matrix.name }}
          path: target/debug/smartboard*
          if-no-files-found: error

      - name: Upload release artifacts
        uses: actions/upload-artifact@v6
        with:
          name: release-${{ matrix.name }}
          path: target/release/smartboard*
          if-no-files-found: error

      - name: Upload small release artifacts
        uses: actions/upload-artifact@v6
        with:
          name: release-small-${{ matrix.name }}
          path: target/release-small/smartboard*
          if-no-files-found: error
